USE bookbyte;
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'admin123';

DROP TABLE IF EXISTS `DETALLE_ORDEN`;
DROP TABLE IF EXISTS `ORDEN`;
DROP TABLE IF EXISTS `C_METODO_PAGO`;
DROP TABLE IF EXISTS `domicilios`;
DROP TABLE IF EXISTS `carrito`;
DROP TABLE IF EXISTS `disponibles`;
DROP TABLE IF EXISTS `libros`;
DROP TABLE IF EXISTS `users`;

CREATE TABLE `users`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `libros`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Autor` VARCHAR(50) NOT NULL,
  `GENERO` VARCHAR(40) NOT NULL,
  `PRECIO` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `disponibles`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `idLibro` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `disponibles_libro` FOREIGN KEY (`idLibro`) REFERENCES `libros` (`id`)
);

CREATE TABLE `carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idLibro` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `carrito_user_idx` (`idCliente`),
  KEY `libro_idx` (`idLibro`),
  CONSTRAINT `carrito_user` FOREIGN KEY (`idCliente`) REFERENCES `users` (`id`),
  CONSTRAINT `carrito_libro` FOREIGN KEY (`idLibro`) REFERENCES `libros` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `domicilios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `ESTADO` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45),
  `CP` VARCHAR(10),
  `TELEFONO` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ID_CLIENTE` (`idCliente`),
  CONSTRAINT `ID_CLIENTE` FOREIGN KEY (`idCliente`) REFERENCES `users` (`id`)
);
DROP TABLE IF EXISTS `C_METODO_PAGO`;
CREATE TABLE `C_METODO_PAGO`(
	`id` INT NOT NULL AUTO_INCREMENT,
    `TIPO` VARCHAR(40) NOT NULL,
    PRIMARY KEY (`id`)
);
INSERT INTO `C_METODO_PAGO` (`TIPO`) VALUES
('OXXO'), 
('PAYPAL'), 
('TARJETA');

DROP TABLE IF EXISTS `ORDEN`;
CREATE TABLE `ORDEN`(
`id` INT NOT NULL AUTO_INCREMENT,
`ID_USUARIO` INT NOT NULL,
`ID_METODO_PAGO` INT NOT NULL,
`TOTAL` DECIMAL(10,2) NOT NULL,
`ID_DOMICILIO` INT NOT NULL,
PRIMARY KEY(`id`),
KEY `ID_USUARIO` (`ID_USUARIO`),
KEY `ID_METODO_PAGO` (`ID_METODO_PAGO`),
KEY `ID_DOMICILIO` (`ID_DOMICILIO`),
CONSTRAINT `ID_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `users` (`id`),
CONSTRAINT `ID_METODO_PAGO` FOREIGN KEY (`ID_METODO_PAGO`) REFERENCES `C_METODO_PAGO` (`id`),
CONSTRAINT `ID_DOMICILIO` FOREIGN KEY (`ID_DOMICILIO`) REFERENCES `domicilios` (`id`)
);

CREATE TABLE `DETALLE_ORDEN`(
`id` int not null AUTO_INCREMENT,
`ID_ORDEN` INT NOT NULL,
`ID_PRODUCTO` INT NOT NULL,
`CANTIDAD` INT NOT NULL,
`PRECIO` DECIMAL(10,2) NOT NULL,
PRIMARY KEY(`id`),
KEY `ID_ORDEN` (`ID_ORDEN`),
KEY `ID_PRODUCTO` (`ID_PRODUCTO`),
CONSTRAINT `ID_ORDEN` FOREIGN KEY (`ID_ORDEN`) REFERENCES `ORDEN` (`id`),
CONSTRAINT `ID_PRODUCTO` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `libros` (`id`)
);